---
# tasks file for docker

- name: Remove older versions of docker releases if pre-installed.
  apt:
    name: "{{ legacy_releases }}"
    state: absent
    purge: yes

- name: Install packages to allow apt to use a repository over HTTPS.
  apt:
    update_cache: yes
    name: "{{ sys_dependencies }}"

- name: Add APT GPG keyring folder
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Add Docker's official GPG keys.
  apt_key:
    url: "{{ key_url }}"

- name: Update the sources list to find the latest stable release.
  apt_repository:
    repo: "{{ sources_list_entry }}"

- name: Install the latest stable release of Docker community edition.
  apt:
    update_cache: yes
    name: "{{ apt_package_name }}"

- name: Create the docker directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: Configure docker to store it's data on the partition allocated for the service user to prevent disk overflow on the root partition.
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Restart docker service to reflect the changes in configuration.
  service:
    name: docker
    state: restarted

# # DEPRECATED FOR NOW (since deemed unsafe to be enabled by default in a production environment)
- name: Add the service user to the docker group to be able to access the docker control panel.
  user:
    name: "{{ janastu_servu }}"
    groups: docker
    append: yes

- name: Add the common user to the docker group to be able to access the docker control panel.
  user:
    name: janastuops
    groups: docker
    append: yes

